services:
  sf-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./../:/app:cached
    command: sleep infinity
    networks:
      - dev_network
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./../ollama_models:/root/.ollama
    networks:
      - dev_network
    environment:
      - OLLAMA_HOST="0.0.0.0"
    command: ["serve"]

volumes:
  ollama_models:
    driver: local

networks:
  dev_network:
    name: dev_network
    driver: bridge
