name: Local Assistant
version: 1.0.0
schema: v1

models:
  - name: GPT OSS
    provider: ollama
    model: gpt-oss:20b
    apiBase: http://ollama:11434
    roles:
      - chat
      - edit
      - apply
    capabilities: [tool_use]
    keep_alive: "5m"
    defaultCompletionOptions:
      temperature: 0.0

  - name: Qwen2.5 Coder 1.5B (Autocomplete)
    provider: ollama
    model: qwen2.5-coder:1.5b
    apiBase: http://ollama:11434
    roles:
      - autocomplete
    keep_alive: "5m"

  - name: Nomic Embed Text (Embed)
    provider: ollama
    model: nomic-embed-text
    apiBase: http://ollama:11434
    roles:
      - embed
    keep_alive: "5m"

context:
  - provider: code
  - provider: file
  - provider: diff
  - provider: terminal
  - provider: codebase
    params:
      useReranking: false
      nRetrieve: 25
      nFinal: 10

mcpServers:
  - name: Context7 MCP
    type: streamable-http
    url: https://mcp.context7.com/mcp
